### ISSUE TITLE
Liquorix Kernel (5.14.x): Insanely long KVM/Qemu VM boot times vs stock Arch Kernel

### ISSUE THREAD

**Issue by SoftwareGuy** [damentz/liquorix-package#68] opened 2021-10-02 07:41 UTC
Long time Liquorix kernel user reporting in.

I'm seeing some really weird behaviour with using KVM/QEMU at the moment with this kernel. Usually Liquorix is my go-to solution because it brings both speed and other nice features (optimizations, tweaks for maximum performance) to my hardware. However, I'm finding it weird that it's actually causing VMs to boot up very slowly. I booted up a test VM and on the stock Arch Linux kernel, it booted up within 1 minute (by "booted up", I mean to the BIOS screen). 

EDIT: If a VM also reboots (ie. Restart via Windows) it will exhibit the long wait as well.

I don't know how to diagnose it but using Virt-Manager as the "monitor" of the VM, there is a exceptionally long delay between QEMU spawning and output from the actual OVMF UEFI BIOS appearing. This delay is in excess of a minute or two on Liquorix kernel. On stock, it appears within 10 seconds. When it's taking a extremely long time, the CPU core threads that are assigned to QEMU are pegged at 100% until the VM settles and starts working.

This issue seems to have reared itself in the past with what was it... Kernel 5.4? but since I had to then switch to Windows as my workload required it (and the VM setup wasn't sufficient) and I can't remember the last kernel that didn't have the issues.

Software is Arch Linux (latest), QEMU 6.1. 
Hardware is a 12C/24T AMD Ryzen 9 5900X paired with a ASUS X570 Pro-CSM motherboard.
Everything else is stock, no isolated CPUs or memory pinning at this time.

Is there anything I can do to help diagnose, ie. see what's causing QEMU to spin? I hate to think this is one weakness the Liquorix has which is extremely long VM bootup times.

Cheers!

**Comment by damentz** [comment] 2021-10-02 17:50
Hi @SoftwareGuy, can you use **perf** to generate a flamegraph for when using Stock versus Liquorix?  Also, I pushed an update for Liquorix that enables all the tracing functionality since it was off previously that perf needs.

You'll need to run the following during the boot sequence.

1. `sudo perf record -gp <VM pid>` and hit CTRL+C once the boot is complete
2. `sudo perf script | stackcollapse-perf | flamegraph > qemu-flamegraph.svg`

The flamegraph package is available in the AUR at https://aur.archlinux.org/packages/flamegraph-git/, or you can use the official git repo: https://github.com/brendangregg/FlameGraph.

Attach the two SVGs to this issue and I'll take a look at them.

Another thing you can try besides using perf is changing the /proc/sys/kernel/yield_type value.  You can set:

 * 0 - do not yield
 * 1 - deboost
 * 2 - skip task

This may change the behavior of QEMU and fix the issue.

**Comment by SoftwareGuy** [comment] 2021-10-03 04:58
Hi Damentz,

Thanks for the reply! I appreciate it. 😄 

I've changed the yield_type variable from 1, which was "deboost" to "skip task" and VMs on the kernel are literally booting up super quickly now. It's like you just slapped a nitrous tank on QEMU!

Since the VMs are managed by libvirt I will need to fish around for the PID. This may cause my results to not be super accurate, but I will do my best to get you what you need.

**Comment by SoftwareGuy** [comment] 2021-10-03 06:50
Alright, so I updated Arch and pulled in the latest lqx kernel version. 

However, it seems the insanely long behaviour has gone away. Right when I wanted to troubleshoot it, it decides to fix itself or it was fixed somehow in the update... 🤔 

I'm going to keep an eye on this, if the issue doesn't rear its head within the coming days I'll close the ticket.

**Comment by damentz** [comment] 2021-10-03 13:39
Ok, that's good!  It seems like the yield behavior in PDS still behaves similarly to MuQSS.

> However, it seems the insanely long behaviour has gone away. Right when I wanted to troubleshoot it, it decides to fix itself or it was fixed somehow in the update... :thinking: 

That would be ironic if one of the RC stable patches I applied fixed a bug with KVM and resolved this as a side effect.  Maybe instead the issue is sometimes not reproducable?

Speaking of which, if you can reproduce this issue again on yield_type 1, can you also verify what the behavior of 0 is?  On MuQSS, there was a bug where the compromise option (1), created all sorts of strange behavior with RPCS3, a heavy user of `yield_type`.  Switching that value to 0 or 2 fixed the issue, but 1 remained problematic.  I just want to see if that's also the case here with PDS.

EDIT: With what we already learned in this issue, I'll push up a change to Zen Kernel so `yield_type` 2  is selected by default.  On Liquorix 5.13 and earlier, I used zero because MuQSS did such a bad job reusing the same core that throughput would suffer.  But PDS seems to do much better here, so maybe we can get the behavior we want without the speed loss.

**Comment by damentz** [comment] 2021-10-03 14:55
@SoftwareGuy doing some more testing locally, I think I would like to keep `yield_type` as 1 so that wine games don't suffer as much.  As `yield_type` 2, multithreaded wine games and applications suffer quite a bit.

As a test, I loaded Windows 10 into Virt Manager and try rebooting windows with different yield types.  None of the options appears to make a difference with boot times.  However, I'm using a mostly basic installation with QXL and the drivers installed.  Maybe there's something unique about your configuration or is actually is resolved as of the latest Liquorix kernel?

**Comment by SoftwareGuy** [comment] 2021-10-05 02:16
That’s what I’m not sure about to be honest. Maybe it was resolved, maybe it was a side effect that was introduced with another bug and it was patched out of sheer luck?

When I was testing the VMs I was using whatever setting Virt Manager uses as the stock defaults. So I feel we’d almost have the same testing ground.

**Comment by damentz** [comment] 2021-10-05 16:05
> That’s what I’m not sure about to be honest. Maybe it was resolved, maybe it was a side effect that was introduced with another bug and it was patched out of sheer luck?
> 
> When I was testing the VMs I was using whatever setting Virt Manager uses as the stock defaults. So I feel we’d almost have the same testing ground.

Very interesting, well lets keep this issue open until October 11th.  If you can't reproduce it then maybe a stable update I merged resolved the issue.  And that's better anyways, `yield_type` does appear to work in my testing when using `yield` heavy apps, like wine applications.

For example, with cpuz_x64:

1. Using yield type 0, the benchmark portion of this windows application gets the highest benchmark score
2. Using yield type 1, the benchmark suffers about 1% in performance depending on what else is happening on my system
3. Using yield type 2, the benchmark suffers about 20% in multithreaded performance as the scheduler reschedules the application on every `yield` invocation as if the resources of the local system were 100% saturated.

With that in mind, PDS's implementation of yield appears to be working pretty well and I'll be keeping the default as 1.  For individual systems that need a very specific behavior, updating that is as easy as `echo <num> | sudo tee /proc/sys/kernel/yield_type`, or storing `kernel.yield_type = <num>` in /etc/sysctl.d.

**Comment by damentz** [comment] 2021-10-12 15:10
@SoftwareGuy ok, well I think I'll just close this out now.  Liquorix is still using **yield_type** **1**, so nothing has changed as a result of this issue.

If you find a way to reproduce the long boot times more reliably, I'll reopen this issue.

**Closed as completed by damentz** 2021-10-12 15:10 UTC

**Comment by SoftwareGuy** [comment] 2021-10-13 10:08
Hey, sorry for the late reply but yeah, I can't really replicate the fault right now - everything's running very smoothly.

Let's put this one in the freezer and if I encounter the bug again I'll let you know. :)
