### ISSUE TITLE
Problem with pterodactyl

### ISSUE THREAD

**Issue by bubobih** [damentz/liquorix-package#82] opened 2022-02-16 07:18 UTC
Hello, this is the best kernel for games, but it doesent work with pterodactyl wings

https://i.imgur.com/YD2P6Pq.jpeg

container@pterodactyl~ Error Event [65931f5d-358a-49d8-b60f-624c7060a164]: environment/docker: failed to start container: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/system.slice/docker-aaa01f0cc7ab8c2277c05a8ebd7df87073bdc7fb30c4faeeb3c0a9a2ec6fa065.scope/cpu.weight: no such file or directory: unknown

Is there any fix for this? Regards

**Comment by damentz** [comment] 2022-03-03 02:29
Wow, I some how missed this issue when you first opened it.  I opened an issue regarding this issue on the Project C project: https://gitlab.com/alfredchen/linux-prjc/-/issues/51

I'll keep this open for a bit longer so that I can take a stab at implementing a fix myself once I have enough time, but most likely we'll need the author of PDS/BMQ or someone much smarter than me to implement it instead.

**Comment by Maxximou5** [comment] 2022-03-14 20:10
Experiencing the same issue, tried the following versions -

- linux-image-5.10.0-17.1-liquorix-amd64/stable,now 5.10-25.1~bullseye amd64 
- linux-image-5.16.0-14.1-liquorix-amd64/stable,now 5.16-18.1~bullseye amd64 
- linux-image-5.3.0-18.1-liquorix-amd64/stable,now 5.3-15.1~bullseye amd64

All result in the following error -
```
Error Event [c9216a72-62ea-4763-9c96-0e7a3bf123de]: environment/docker: failed to start container: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: open /sys/fs/cgroup/system.slice/docker-e563bf92e8067a31c2a9b3425e435367f07d883965827a354e9512d7beabc4c0.scope/cpu.weight: no such file or directory: unknown
```

```
~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by bubobih** [comment] 2022-03-14 20:31
> Wow, I some how missed this issue when you first opened it. I opened an issue regarding this issue on the Project C project: https://gitlab.com/alfredchen/linux-prjc/-/issues/51
> 
> I'll keep this open for a bit longer so that I can take a stab at implementing a fix myself once I have enough time, but most likely we'll need the author of PDS/BMQ or someone much smarter than me to implement it instead.

No problem :) when u solve or someone else solve it notify us so we can test :)

**Comment by Maxximou5** [comment] 2022-03-14 21:31
Ran the following script to check for cgroup -> [check-config.sh](https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh)
Kernel: Linux 5.16.0-14.2-liquorix-amd64
Output:
```
- cgroup hierarchy: cgroupv2
  Controllers:
  - cpu: available
  - cpuset: available
  - io: available
  - memory: available
  - pids: available
```
```
~# grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
```
Results in:
```
Error Event [06ce567c-5a59-4fcc-b320-d4a14dc6ecb6]: environment/docker: failed to start container: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/system.slice/docker-4e6ebdc964ebcdaf9eecf38badee7c3b48341d068b63115e477c10410678a0a3.scope/cpu.weight: no such file or directory: unknown
```

Docker version: `Docker version 20.10.12, build e91ed57`

**Workaround**:
Setting the following results in the image booting normally...
Use cgroup v1 instead of v2 in `/etc/default/grub`
/etc/default/grub: `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"`
However, docker then is unable to report CPU and MEM usage.
```
CONTAINER ID   NAME                                   CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O   PIDS
340f3f6b22b3   45dac61e-052f-4dcc-8839-9b9c9452f910   0.00%     0B / 0B               0.00%     0B / 0B          0B / 0B     0
```

Issue: https://github.com/pterodactyl/panel/issues/3999
It appears that going back to cgroup v1 causes the issue. Can't go forward to v2 either.

**Comment by damentz** [comment] 2023-12-27 23:39
@bubobih @Maxximou5 could you guys try the latest version of Liquorix?  In the latest update, stubs are now in place for legacy and current groups.  Pterodactyl should work now.

**Comment by Red4Hack** [comment] 2023-12-28 03:27
For me it is already working normally

**Comment by damentz** [comment] 2023-12-31 23:32
@ViniciusRed thanks for the feedback, but I was hoping for results on software that was already not working.  Fortunately, I have a friend that couldn't run Liquorix as his main kernel because of this issue and confirmed his Kubernetes clusters spawn and run properly.

Marking this as resolved.

**Closed as completed by damentz** 2023-12-31 23:32 UTC
Labels: upstream defect
