### ISSUE TITLE
Recent commit broke hugepage support

### ISSUE THREAD

**Issue by portablesounds** [damentz/liquorix-package#85] opened 2022-03-09 18:09 UTC
Hi, I recently updated my kernel and have found that the commit a2254f8ebddc36dd2eaa29c9c30a111106cad3b1: "config: Disable CONFIG_TRANSPARENT_HUGEPAGE" seems to have caused Hugepages to be disabled outright in the kernel:
```
$ sudo hugeadm --explain
hugeadm:ERROR: kernel does not support huge pages
```
According to Oracle docs (https://docs.oracle.com/database/121/UNXAR/appi_vlm.htm#UNXAR402), enabling these two config flags in the kernel should re-enable it:
`CONFIG_HUGETLBFS and CONFIG_HUGETLB_PAGE`

**Comment by damentz** [comment] 2022-03-09 18:33
Are you currently using huge pages for anything or just want to enable them?  Huge page support was removed for two reasons:

1. Using huge pages increases the chance that kcompactd goes crazy and makes interactive applications become unresponsive.  This became more obvious to me after proactive compaction was merged into mainline and I had to chase down what was causing it.  Disabling CONFIG_TRANSPARENT_HUGEPAGE prevents any distro from accidentally enabling it and making the experience on Liquorix miserable for the unknowing.
2. Disabling CONFIG_HUGETLBFS reduces the default page block size for the kernel, making new memory allocations quicker: https://github.com/kerneltoast/kernel_x86_laptop/commit/a99643b271886b3c17c25ed95c662e5e24c74e1f

Liquorix is tuned aggressively to be more deterministic, that means sacrificing some throughput to get a more consistently responsive desktop (and lower scheduling latency whenever possible).  Disabling these two options was a bit overdue, but some recent experiences with huge pages on my end made me realize how big of a impact they have, usually at the most inconvenient times.

As for any application that may need them, it's normally completely optional and most software falls back to regular pages automatically.  Worst case you can probably find a config to adjust if that's not the case.

**Comment by portablesounds** [comment] 2022-03-09 18:54
Ah I see. Currently I'm using hugepages to allocate a large chunk of memory to my VM, which greatly speeds up memory access for the VM. If this is too niche of a use-case, that's totally valid and I can build zen-kernel with this flag enabled for myself.

**Comment by damentz** [comment] 2022-03-09 21:17
Ok, after some more thinking, I'm turning huge page support back on.  I'll spend some more time researching about the impact of various options and see if I can get the impact I'm looking for without the collateral damage caused by disabling the interface entirely.

Next kernel coming out in up to 2 hours will restore huge page support.

**Comment by portablesounds** [comment] 2022-03-09 21:21
Awesome! I appreciate it. There seem to be a lot of methods to tune hugepages once it's enabled, so I think there can still be a balance struck while allowing for hugepage usage.

**Closed as completed** 2022-03-09 21:21 UTC
