### ISSUE TITLE
ERROR (dkms apport): kernel package linux-headers-6.0.0-6.1-liquorix-amd64 is not supported

### ISSUE THREAD

**Issue by Marietto2008** [damentz/liquorix-package#113] opened 2022-10-30 14:44 UTC
Hello.

I'm running ubuntu 22.04 with kernel version "6.0.0-6.1-liquorix-amd64" ; I would like to mount my zfs volume that usually I do with this command :

`# sudo zpool import -f -R /mnt/freebsd-zfs zroot2 `

unfortunately it won't work if I'm running a liquorix kernel. The errors reported are the following :

```
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

# sudo modprobe zfs

modprobe: FATAL: Module zfs not found in directory /lib/modules/6.0.0-6.1-liquorix-amd64

# sudo apt install zfs-dkms

Loading new zfs-2.1.4 DKMS files...
Building for 6.0.0-6.1-liquorix-amd64
Building initial module for 6.0.0-6.1-liquorix-amd64
configure: error: 
        *** Unable to build an empty module.

ERROR (dkms apport): kernel package linux-headers-6.0.0-6.1-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 6.0.0-6.1-liquorix-amd64 (x86_64)
Consult /var/lib/dkms/zfs/2.1.4/build/make.log for more information.
dpkg: errore nell'elaborare il pacchetto zfs-dkms (--configure):
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

how to fix this ?

**Comment by Rongronggg9** [comment] 2022-10-30 14:54
> Consult `/var/lib/dkms/zfs/2.1.4/build/make.log` for more information.

**Comment by Marietto2008** [comment] 2022-10-30 15:18
```
DKMS make.log for zfs-2.1.4 for kernel 6.0.0-6.1-liquorix-amd64 (x86_64)
Sun Oct 30 12:42:47 PM CET 2022
Make ***No targets specified and no makefiles found. Stop.
```

**Comment by Rongronggg9** [comment] 2022-10-30 15:42
```
Loading new zfs-2.1.6 DKMS files...
Building for 6.0.0-6.1-liquorix-amd64
Building initial module for 6.0.0-6.1-liquorix-amd64
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<stdin>:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<stdin>:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<stdin>:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<stdin>:3: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<stdin>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<stdin>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Done.

zavl.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

znvpair.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

zunicode.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

zcommon.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

zfs.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

icp.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

zlua.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

spl.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/

zzstd.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.0.0-6.1-liquorix-amd64/updates/dkms/
depmod......
update-initramfs: Generating /boot/initrd.img-6.0.0-6.1-liquorix-amd64
```

2.1.4 is too old, 2.1.6 got its initial support for Linux 6.0, but not complete support (plz wait for the next release: https://github.com/openzfs/zfs/pull/14091).

**Comment by Marietto2008** [comment] 2022-10-30 15:50
Should I install zfs-dkms 2.1.6 on ubuntu 22.04 ? can I  get it from here ? ---> https://debian.pkgs.org/sid/debian-contrib-amd64/zfs-dkms_2.1.6-2_all.deb.html or from somewhere else place ?

**Comment by Rongronggg9** [comment] 2022-10-30 15:56
If you could install it successfully, it should work "as is", but there is no warranty.

**Comment by Marietto2008** [comment] 2022-10-30 15:56
```
# apt remove zfsutils-linux zfs-dkms
# dpkg -i zfs-dkms_2.1.6-2_all.deb
Selezionato il pacchetto zfs-dkms non precedentemente selezionato.
(Lettura del database... 648681 file e directory attualmente installati.)
Preparativi per estrarre zfs-dkms_2.1.6-2_all.deb...
Estrazione di zfs-dkms (2.1.6-2)...
Configurazione di zfs-dkms (2.1.6-2)...
Loading new zfs-2.1.6 DKMS files...
Building for 6.0.0-6.1-liquorix-amd64
Building initial module for 6.0.0-6.1-liquorix-amd64
configure: error: 
                *** This kernel does not include the required loadable module
                *** support!
                ***
                *** To build OpenZFS as a loadable Linux kernel module
                *** enable loadable module support by setting
                *** `CONFIG_MODULES=y` in the kernel configuration and run
                *** `make modules_prepare` in the Linux source tree.
                ***
                *** If you don't intend to enable loadable kernel module
                *** support, please compile OpenZFS as a Linux kernel built-in.
                ***
                *** Prepare the Linux source tree by running `make prepare`,
                *** use the OpenZFS `--enable-linux-builtin` configure option,
                *** copy the OpenZFS sources into the Linux source tree using
                *** `./copy-builtin <linux source directory>`,
                *** set `CONFIG_ZFS=y` in the kernel configuration and compile
                *** kernel as usual.

ERROR (dkms apport): kernel package linux-headers-6.0.0-6.1-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 6.0.0-6.1-liquorix-amd64 (x86_64)
Consult /var/lib/dkms/zfs/2.1.6/build/make.log for more information.
```
what to do now ?

**Comment by Rongronggg9** [comment] 2022-10-30 16:07
Ah uh, I am not very sure why the error occurred, try `apt install ./zfs-dkms_2.1.6-2_all.deb` instead of `dpkg -i zfs-dkms_2.1.6-2_all.deb` in case there are unmet dependencies?

And your `/var/lib/dkms/zfs/2.1.6/build/make.log`?

**Comment by Marietto2008** [comment] 2022-10-30 16:14
I suspect that it happens because in the liquorix kernel config file the parameter "CONFIG_ZFS=y" is not enabled. To be honest,there isn't any entry called "ZFS" inside of it. I've extracted the kernel config file with the command "zcat /proc/config.gz > .config" ; so,now I have added that parameter and I need to recompile the kernel,using these commands :
```

# Create a directory and move into it.
mkdir ~/linux_source && cd !_

# Get the kernel source.
https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.0.1.tar.gz

# Get the liquorix patch
where ?

# Get the config ***PICK THE CORRECT ONE FOR YOUR ARCH***
where ?
```

where I'm reading how to do it ---> https://ubuntuforums.org/archive/index.php/t-2136818.html

**Comment by Rongronggg9** [comment] 2022-10-30 16:25
> I suspect that it happens because in the liquorix kernel config file the parameter "CONFIG_ZFS=y" is not enabled.

Nope. The flag is to build ZFS support into the kernel, instead of DKMS support. In most cases, building ZFS support (licensed under CDDL) into the kernel (licensed under GPLv2) results in license conflict. As a result, liquorix could probably NOT do this.

I believe liquorix has enabled DKMS support, this may be a wrong error prompt (and your problem may be toolchain related as you are installing a Debian package on Ubuntu).

> To be honest,there isn't any entry called "ZFS" inside of it.

That's what is right. ZFS is NOT a part of the Linux source tree.

**Comment by Marietto2008** [comment] 2022-10-30 16:25
```
/var/lib/dkms/zfs/2.1.6/build/make.log

DKMS make.log for zfs-2.1.6 for kernel 6.0.0-6.1-liquorix-amd64 (x86_64)
Sun Oct 30 05:11:02 PM CET 2022
Make ***No targets specified and no makefiles found. Stop.
```

**Comment by Marietto2008** [comment] 2022-10-30 16:29
I know man. But I'm trying to follow the easiest route. Liquorix can't do that,ok,can I do that,under my responsability ? That's because I will not re-distribute anything,I'm not a developer.

**Comment by Rongronggg9** [comment] 2022-10-30 16:31
I suggest you just wait for the next release of `zfs-dkms` as 2.1.6 does not support Linux 6.0 "officially" but the next release will. Maybe it is a coincidence that I could install it on Linux 6.0.

**Comment by Marietto2008** [comment] 2022-10-30 16:35
I can't wait. I need to access the informations stored on my ZFS volume as soon as possible. And I can't use another kernel,because usually I make a strong use of virtualization and the liquorix kernel is good for that.

**Comment by damentz** [comment] 2022-10-30 16:35
> Nope. The flag is to build ZFS support into the kernel, instead of DKMS support. In most cases, building ZFS support (licensed under CDDL) into the kernel (licensed under GPLv2) results in license conflict. As a result, liquorix could probably NOT do this.

@Rongronggg9 is correct, I legally cannot distribute ZFS with Liquorix.  This is also why you don't see any stock or custom kernels with ZFS baked in as well.

@Marietto2008 it's not good practice to mix Debian and Ubuntu packages since changes in package names or dependencies can leave your system in a unmaintainable state.  With that said, there appears to be a PPA for Ubuntu Focal that backports the latest stable version of ZFS that _may_ support kernel 6.0 with the proper name Ubuntu wants (**zfs-linux**): https://launchpad.net/~jonathonf/+archive/ubuntu/zfs?field.series_filter=focal

If this doesn't work, my only recommendation is that you migrate to a rolling release distribution that does a good job keeping DKMS modules up to date.  The most obvious choice is Arch Linux and any of its spins that reference the core repositories (Manjaro's unstable branch also works here).  Otherwise, since you depend on ZFS for your day to day, you may want to stay on a stock kernel or move the ZFS storage over to a dedicated machine, like a NAS, where custom kernels really aren't necessary.

**Comment by Rongronggg9** [comment] 2022-10-30 16:44
> I can't wait.

I am not sure if this will help, but you could try:

```console
# apt install ./zfs-dkms_2.1.6-2_all.deb  # or the PPA @damentz mentioned
...it should fail...

# sed -i 's/5.19/6.0/g' /usr/src/zfs-2.1.6/META

# apt install --fix-broken
```

> And I can't use another kernel,because usually I make a strong use of virtualization and the liquorix kernel is good for that.

You may downgrade liquorix kernel:
```console
# apt install linux-image-5.19.0-17.2-liquorix-amd64 linux-headers-5.19.0-17.2-liquorix-amd64
# apt remove linux-image-6.0.0-*-liquorix-amd64 linux-headers-6.0.0-*-liquorix-amd64
# apt remove zfs-dkms
# apt install zfs-dkms
```

Then wait for the next release of `zfs-dkms`. After that, you can:

```
# apt install linux-image-liquorix-amd64 linux-headers-liquorix-amd64
# apt install zfs-dkms
```

**Comment by Marietto2008** [comment] 2022-10-30 16:50
After the installation of this PPA : 

https://launchpad.net/~jonathonf/+archive/ubuntu/zfs?field.series_filter=focal

this is what happened :

```
Configurazione di zfsutils-linux (2.1.6-0york1~22.04)...
modprobe: FATAL: Module zfs not found in directory /lib/modules/6.0.0-6.1-liquorix-amd64
zfs-import-scan.service is a disabled or a static unit, not starting it.
Configurazione di zfs-dkms (2.1.6-0york1~22.04)...
Loading new zfs-2.1.6 DKMS files...
Building for 6.0.0-6.1-liquorix-amd64
Building initial module for 6.0.0-6.1-liquorix-amd64
configure: error: 
                *** This kernel does not include the required loadable module
                *** support!
                ***
                *** To build OpenZFS as a loadable Linux kernel module
                *** enable loadable module support by setting
                *** `CONFIG_MODULES=y` in the kernel configuration and run
                *** `make modules_prepare` in the Linux source tree.
                ***
                *** If you don't intend to enable loadable kernel module
                *** support, please compile OpenZFS as a Linux kernel built-in.
                ***
                *** Prepare the Linux source tree by running `make prepare`,
                *** use the OpenZFS `--enable-linux-builtin` configure option,
                *** copy the OpenZFS sources into the Linux source tree using
                *** `./copy-builtin <linux source directory>`,
                *** set `CONFIG_ZFS=y` in the kernel configuration and compile
                *** kernel as usual.

ERROR (dkms apport): kernel package linux-headers-6.0.0-6.1-liquorix-amd64 is not supported
Error! Bad return status for module build on kernel: 6.0.0-6.1-liquorix-amd64 (x86_64)
```

Regarding the license violation,you say that  you cannot distribute ZFS with Liquorix. Ok. don't do that,just explain to me how to do it.

**Comment by Marietto2008** [comment] 2022-10-30 16:58
I've modified the META file,but nothing,I've got the same error. No,I don't want to downgrade the liquorix kernel. I don't want to use old stuff. So,if @damentz wants to explain to me how to add the zfs support embedded inside the liquorix kernel,I will try,otherwise,I will give it up. Anyway,I've found what are the steps to follow,I just need to have the missing informations below :

```
# Create a directory and move into it.
mkdir ~/linux_source && cd !_

# Get the kernel source.
https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.0.1.tar.gz

# Get the liquorix patch
where ?

# Get the config ***PICK THE CORRECT ONE FOR YOUR ARCH***
where ?

```
where I'm reading how to do it ---> https://ubuntuforums.org/archive/index.php/t-2136818.html

**Comment by Rongronggg9** [comment] 2022-10-30 17:14
Alternatively, you can try building a snapshot of `zfs-dkms` (should support Linux 6.0):

```console
$ sudo apt install build-essential autoconf automake libtool gawk alien fakeroot dkms libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev libattr1-dev libelf-dev linux-headers-generic python3 python3-dev python3-setuptools python3-cffi libffi-dev python3-packaging
$ git clone https://github.com/openzfs/zfs.git
$ cd zfs
$ ./autogen.sh
$ ./configure --enable-systemd
$ make -j1 deb-utils deb-dkms
$ sudo apt-get install dkms
$ for file in *.deb; do sudo gdebi -q --non-interactive $file; done
```

https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html#debian-and-ubuntu

**Comment by Rongronggg9** [comment] 2022-10-30 17:17
> Get the liquorix patch

https://github.com/zen-kernel/zen-kernel/releases/tag/v6.0.6-lqx1

> Get the config ***PICK THE CORRECT ONE FOR YOUR ARCH***

https://github.com/damentz/liquorix-package/blob/6.0/master/linux-liquorix/debian/config/kernelarch-x86/config-arch-64

**Comment by damentz** [comment] 2022-10-30 17:31
@Marietto2008 I'm going to close out this issue.  The issue here is not Liquorix, but the distribution you're running and the available packages for ZFS.

You have a few solutions:
1. Downgrade to the last 5.19 kernel and wait for a backport of 2.1.7 from the PPA I linked.
2. Switch to a Arch Linux or a spin of it where these issues don't happen.  I confirmed by installing the **zfs-dkms** AUR package and it builds and installs without error [1]
3. Figure out how to patch the Ubuntu variation of the **zfs-linux** package to not fail installing on Linux 6.0.  This part is confusing because Arch does not patch ZFS, yet the DKMS installer succeeds.  Most likely the maintainer(s) added some unnecessary validation code that's buggy and causes the module to fail building.

Also last, it's disrespectful to multi post.  I recommend you close out the issue you opened on the official project, as it's not their problem to solve (it's already fixed in master): https://github.com/openzfs/zfs/issues/14114

[1]
```
(2/3) Install DKMS modules
==> dkms install --no-depmod zfs/2.1.6 -k 6.0.5-arch1-1
fgrep: warning: fgrep is obsolescent; using grep -F
==> dkms install --no-depmod zfs/2.1.6 -k 6.0.6-lqx1-1-lqx
fgrep: warning: fgrep is obsolescent; using grep -F
==> depmod 6.0.5-arch1-1
==> depmod 6.0.6-lqx1-1-lqx
```

**Closed as not planned by damentz** 2022-10-30 17:31 UTC
Labels: wontfix, upstream defect

**Comment by Marietto2008** [comment] 2022-10-30 17:37
It's not a good idea to close it,because I can try the other roads suggested by you. If you close the thread,I will do this for my own without sharing what I achieve.

**Comment by damentz** [comment] 2022-10-31 00:44
@Marietto2008 I just deleted your post at https://github.com/damentz/liquorix-package/issues/114 requesting tech support.  If you need help with the ZFS module, you'll get more help posting to the forum for your distribution.  Further posts asking for help unrelated to Liquorix will get deleted and/or reported for abusive behavior.

**Comment by Marietto2008** [comment] 2022-10-31 01:04
On askubuntu they are not interested to help,you can see by yourself....

https://askubuntu.com/questions/1438176/error-dkms-apport-kernel-package-linux-headers-6-0-0-6-1-liquorix-amd64-is-no
