### ISSUE TITLE
Problem cgroup

### ISSUE THREAD

**Issue by Red4Hack** [damentz/liquorix-package#152] opened 2023-12-26 22:51 UTC
I had this problem recently and it's normal for this to happen, it works on the normal version of Linux
![image](https://github.com/damentz/liquorix-package/assets/81523685/03c65f9e-d4f9-4d92-a5c2-38ed80c0c511)

**Comment by damentz** [comment] 2023-12-26 23:36
This is a duplicate of https://github.com/damentz/liquorix-package/issues/82.  Still need to see what the difficulty is in adding stubs to Project-C.

**Comment by damentz** [comment] 2023-12-31 23:33
FYI in-case you're not aware, this issue should be resolved as of the latest Liquorix kernel release.  Stubs were added so these missing files accept input and respond with a stubbed out value.

**Comment by damentz** [comment] 2023-12-31 23:33
Marking properly as resolved

**Closed as completed by damentz** 2023-12-31 23:33 UTC
