### ISSUE TITLE
Wakeup from S3 suspend broken with 5.6.0-10.x

### ISSUE THREAD

**Issue by roooots** [damentz/liquorix-package#30] opened 2020-05-07 06:30 UTC
Hi all,

first of all - THANKS for providing this awesome kernel that I've been using for more than a year now!

However, for me a little bug popped up when transitioning from 5.6.0-8 to 5.6.0-10.x which broke ACPI wakeup from suspend via USB, for example an USB mouse.

Expected behaviour: After sending the machine to S3 suspend, it can be woken up by single button click on a mouse connected to the USB controller.
Observed behaviour: After sending the machine to S3 suspend, the machine does not wake up with any action of the aforementioned mouse, but needs a power button press.

This bug is observed with both Ubuntu 18.04 and 20.04. I suspect this is somehow associated with the introduction of tickless idle, although I only have a rough idea of what that actually means. Are there any ideas to solve or work around it?

Cheers,
r.

**Comment by roooots** [comment] 2020-05-07 12:00
Same with 5.6.0-11.1. I tried "nothreadirq" as mentioned in another post, just guessing that it might do the trick, but it did not.

**Comment by damentz** [comment] 2020-05-07 14:00
Hmm, that's interesting that `nothreadirqs` doesn't help.  Did you try the plural form or singular?  If you used the singular version `nothreadirq`, it won't activate:

```
kernel/irq/manage.c
40:early_param("nothreadirqs", setup_noforced_irqthreads);
```

Also, can you try booting and then suspending with `nohz=off`?  If this fixes suspend I may need to temporarily switch back to 250hz with periodic tick.

**Comment by roooots** [comment] 2020-05-07 14:55
Hi, 
thanks for the quick feedback.

The singular in my post was a typo, I used `nothreadirqs`. I've also tried with `nohz=off`, both exclusively and in combination with `nothreadirqs` but the wakeup via USB did not work. I've only tried with 5.6.0-11.1 now, if you want me to try with 5.6.0-10.x please let me know. The same goes if you want me to try any other stuff to debug this issue ;-)


Cheers,
r.

**Comment by roooots** [comment] 2020-05-08 09:48
Nope - (un)fortunately 5.6.0-11.2 does not solve the issue, even with `nothreadirqs`.

**Comment by damentz** [comment] 2020-05-08 16:34
Interesting, this means the bug is caused by an upstream stable patch.  Your best bet in this case would be to run an older kernel until the offending patch is reverted/fixed.

Although, it just occurred to me, I'm not sure what you're seeing is technically a bug, but a mismatch on expected behavior.

> Expected behaviour: After sending the machine to S3 suspend, it can be woken up by single button click on a mouse connected to the USB controller.
> Observed behaviour: After sending the machine to S3 suspend, the machine does not wake up with any action of the aforementioned mouse, but needs a power button press.
> 
> This bug is observed with both Ubuntu 18.04 and 20.04. I suspect this is somehow associated with the introduction of tickless idle, although I only have a rough idea of what that actually means. Are there any ideas to solve or work around it?

What happens if you try resuming your machine by hitting a key on your keyboard or the power button on the machine itself?

I personally don't use suspend on my desktop but I do use it on my laptops, and for my laptops I open the lid to resume.  If for some reason I closed/opened too fast and the laptop is still in suspend, I resume by hitting the power button.  It actually never occurred to me to hit a key on the keyboard or to try activating it with a device I have plugged in.

**Comment by roooots** [comment] 2020-05-09 09:27
Hi,

I'm running a desktop PC and my Z370-based Mobo has 2 USB controllers: One Intel USB 3.0 xHCI Controller and one ASMedia USB 3.1 Controller. The "wakeup mouse" is connected to the ASMedia Controller. Wakeup from suspend does still work with any USB devices connected to the Intel USB 3.0 xHCI Controller and by pressing the power button. The reason why I'm not using the Intel controller for wakeup by default is that, a KVM switch is connected to this controller which does periodic polling and thus causes the PC to wakeup right after it went to S3. The KVM, however, won't play with the ASMedia Controller. Bit of a weird setup, I know... ;-)

Any suggestions where I would properly report this issue?

Cheers,
r.

**Comment by damentz** [comment] 2020-05-27 17:05
I forgot to ask, but have you tried the latest kernel? (5.6-15 / 5.6.0-14.1)  I added a release candidate patch that looked related to what you were experiencing:

```
From 705e20f112327326c5d5e8e7803171827b411055 Mon Sep 17 00:00:00 2001
From: Sasha Levin <sashal@kernel.org>
Date: Fri, 15 May 2020 12:58:19 +0200
Subject: ACPI: EC: PM: Avoid flushing EC work when EC GPE is inactive

From: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

[ Upstream commit 607b9df63057a56f6172d560d5366cca6a030c76 ]

Flushing the EC work while suspended to idle when the EC GPE status
is not set causes some EC wakeup events (notably power button and
lid ones) to be missed after a series of spurious wakeups on the Dell
XPS13 9360 in my office.

If that happens, the machine cannot be woken up from suspend-to-idle
by the power button or lid status change and it needs to be woken up
in some other way (eg. by a key press).

Flushing the EC work only after successful dispatching the EC GPE,
which means that its status has been set, avoids the issue, so change
the code in question accordingly.

Fixes: 7b301750f7f8 ("ACPI: EC: PM: Avoid premature returns from acpi_s2idle_wake()")
Cc: 5.4+ <stable@vger.kernel.org> # 5.4+
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Tested-by: Chris Chiu <chiu@endlessm.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>
---
 drivers/acpi/ec.c    |  6 +++++-
 drivers/acpi/sleep.c | 15 ++++-----------
 2 files changed, 9 insertions(+), 12 deletions(-)

diff --git a/drivers/acpi/ec.c b/drivers/acpi/ec.c
index 03b3067811c9..2713ddb3348c 100644
--- a/drivers/acpi/ec.c
+++ b/drivers/acpi/ec.c
@@ -2064,9 +2064,13 @@ bool acpi_ec_dispatch_gpe(void)
 	 * to allow the caller to process events properly after that.
 	 */
 	ret = acpi_dispatch_gpe(NULL, first_ec->gpe);
-	if (ret == ACPI_INTERRUPT_HANDLED)
+	if (ret == ACPI_INTERRUPT_HANDLED) {
 		pm_pr_dbg("EC GPE dispatched\n");
 
+		/* Flush the event and query workqueues. */
+		acpi_ec_flush_work();
+	}
+
 	return false;
 }
 #endif /* CONFIG_PM_SLEEP */
diff --git a/drivers/acpi/sleep.c b/drivers/acpi/sleep.c
index 3850704570c0..fd9d4e8318e9 100644
--- a/drivers/acpi/sleep.c
+++ b/drivers/acpi/sleep.c
@@ -980,13 +980,6 @@ static int acpi_s2idle_prepare_late(void)
 	return 0;
 }
 
-static void acpi_s2idle_sync(void)
-{
-	/* The EC driver uses special workqueues that need to be flushed. */
-	acpi_ec_flush_work();
-	acpi_os_wait_events_complete(); /* synchronize Notify handling */
-}
-
 static bool acpi_s2idle_wake(void)
 {
 	if (!acpi_sci_irq_valid())
@@ -1018,7 +1011,7 @@ static bool acpi_s2idle_wake(void)
 			return true;
 
 		/*
-		 * Cancel the wakeup and process all pending events in case
+		 * Cancel the SCI wakeup and process all pending events in case
 		 * there are any wakeup ones in there.
 		 *
 		 * Note that if any non-EC GPEs are active at this point, the
@@ -1026,8 +1019,7 @@ static bool acpi_s2idle_wake(void)
 		 * should be missed by canceling the wakeup here.
 		 */
 		pm_system_cancel_wakeup();
-
-		acpi_s2idle_sync();
+		acpi_os_wait_events_complete();
 
 		/*
 		 * The SCI is in the "suspended" state now and it cannot produce
@@ -1060,7 +1052,8 @@ static void acpi_s2idle_restore(void)
 	 * of GPEs.
 	 */
 	acpi_os_wait_events_complete(); /* synchronize GPE processing */
-	acpi_s2idle_sync();
+	acpi_ec_flush_work(); /* flush the EC driver's workqueues */
+	acpi_os_wait_events_complete(); /* synchronize Notify handling */
 
 	s2idle_wakeup = false;
 
-- 
2.25.1
```

**Comment by damentz** [comment] 2020-05-27 17:09
As far as how to report, it looks like someone already submitted a bug that looks similar to what you reported: [Bug 207883 - Regression: USB (XHCI) controller not responding after suspend/wake](https://bugzilla.kernel.org/show_bug.cgi?id=207883)

**Comment by roooots** [comment] 2020-05-31 20:06
Hi,
yes, I'm running the latest 5.6.0-14.1-liquorix-amd64 but the bug persists.
Thanks for the pointers to the above bug report. Although it seems not exactly spot-on, I'll keep an eye on it.

Cheers,
r.

**Comment by damentz** [comment] 2020-06-12 18:48
Marking as resolved since this isn't specific to Liquorix, but an upstream issue.

**Closed as completed by damentz** 2020-06-12 18:48 UTC
