### ISSUE TITLE
Issue with certain WLAN cards from Realtek

### ISSUE THREAD

**Issue by TwilightRavens** [damentz/liquorix-package#71] opened 2021-11-08 21:23 UTC
This problem is also persistent in the Zen kernel, Realtek Semiconductor Co., Ltd. RTL8822CE 802.11ac PCIe Wireless Network Adapter does not reconnect nor can it find any wireless networks after resuming from sleep/suspend in Ubuntu 20.04 and 21.10 using latest liquorix release. Only way to fix is by full system reboot. Full system is: ASUS TUF A15 laptop, Ryzen 5 4600H with Radeon Graphics, 16GB dual channel 3200MHz DDR4, Nvidia GTX 1650 with Realtek  RTL8822CE 802.11ac PCIe Wireless Network Adapter

**Comment by damentz** [comment] 2021-11-09 01:13
Closing this since it appears to be a duplicate of https://github.com/zen-kernel/zen-kernel/issues/255

**Closed as completed by damentz** 2021-11-09 01:13 UTC
