### ISSUE TITLE
Weird Boot Up Error

### ISSUE THREAD

**Issue by Tenebris-Umbra** [damentz/liquorix-package#109] opened 2022-10-13 16:42 UTC
On 5.19.14-4 and 5.19.15-1 I'm getting this error at boot-up, i believe it printed on the screen a total of 12 times  although everything seems to be working fine

 Invalid ELF header magic: != ELF

**Comment by damentz** [comment] 2022-10-13 17:38
Do you have any information I can go off of, like your distro, system, version, etc...

`inxi -b` is a good start.

**Comment by Tenebris-Umbra** [comment] 2022-10-14 00:10
Here Some Info as requested

https://pastebin.com/NzjLbBK6

EDIT: pastebin contents below

```
System:
  Kernel: 5.19.0-15.1-liquorix-amd64 arch: x86_64 bits: 64 compiler: gcc
    v: 10.2.1 Desktop: Cinnamon v: 5.4.12 tk: GTK v: 3.24.24 vt: 7 dm: LightDM
    v: 1.26.0 Distro: LMDE 5 Elsie base: Debian 11.2 bullseye
Machine:
  Type: Desktop System: HP-Pavilion product:  v: N/A
    serial: <superuser required> Chassis: Hewlett-Packard type: 3
    serial: <superuser required>
  Mobo: PEGATRON model: Benicia v: 1.01 serial: <superuser required>
    BIOS: American Megatrends v: 5.30 date: 09/05/2008
CPU:
  Info: quad core model: Intel Core2 Quad Q8200 bits: 64 type: MCP
    smt: <unsupported> arch: Penryn level: v2 rev: 7 cache: L1: 256 KiB
    L2: 4 MiB
  Speed (MHz): avg: 2237 high: 2333 min/max: 2000/2333 cores: 1: 2333
    2: 2247 3: 2217 4: 2154 bogomips: 18666
  Flags: ht lm nx pae sse sse2 sse3 sse4_1 ssse3
Graphics:
  Device-1: NVIDIA GF119 [GeForce GT 610] vendor: PNY driver: nvidia
    v: 390.154 arch: Fermi pcie: speed: 2.5 GT/s lanes: 16 bus-ID: 03:00.0
    chip-ID: 10de:104a class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 with: Xwayland driver: X:
    loaded: nvidia gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 101 s-size: 483x272mm (19.02x10.71")
    s-diag: 554mm (21.82")
  Monitor-1: HDMI-0 res: 1920x1080 hz: 60 dpi: 102
    size: 476x268mm (18.74x10.55") diag: 546mm (21.51") modes: N/A
  OpenGL: renderer: GeForce GT 610/PCIe/SSE2 v: 4.6.0 NVIDIA 390.154
    direct render: Yes
Audio:
  Device-1: Intel 82801I HD Audio vendor: Hewlett-Packard Asus IPIBL-LB
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 chip-ID: 8086:293e
    class-ID: 0403
  Device-2: NVIDIA GF119 HDMI Audio vendor: PNY driver: snd_hda_intel
    v: kernel pcie: speed: 2.5 GT/s lanes: 16 bus-ID: 03:00.1
    chip-ID: 10de:0e08 class-ID: 0403
  Sound Server-1: ALSA v: k5.19.0-15.1-liquorix-amd64 running: yes
  Sound Server-2: PulseAudio v: 14.2 running: no
  Sound Server-3: PipeWire v: 0.3.58 running: yes
Network:
  Device-1: Qualcomm Atheros AR5413/AR5414 Wireless Network Adapter [AR5006X
    802.11abg] vendor: Lite-On WN5301A 802.11bg driver: ath5k v: kernel
    bus-ID: 01:00.0 chip-ID: 168c:001b class-ID: 0200
  IF: wlp1s0 state: up mac: <filter>
RAID:
  Hardware-1: Intel SATA Controller [RAID mode] driver: ahci v: 3.0
    port: d080 bus-ID: 00:1f.2 chip-ID: 8086:2822 rev: N/A class-ID: 0104
Drives:
  Local Storage: total: 1.36 TiB used: 802.68 GiB (57.4%)
  Swap:
  ID-1: swap-1 type: partition size: 6.15 GiB used: 0 KiB (0.0%) priority: -2
Sensors:
  System Temperatures: cpu: 68.0 C mobo: N/A gpu: nvidia temp: 56 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 40%
Repos:
  Packages: pm: dpkg pkgs: 2644
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/Emulators:Wine:Debian.list
    1: deb http://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_11/ /
  No active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome-beta.list
    1: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list
    1: deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main
  No active apt repos in: /etc/apt/sources.list.d/linuxuprising-java.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com elsie main upstream import backport romeo
    2: deb https://deb.debian.org/debian/ bullseye main contrib non-free
    3: deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
    4: deb http://security.debian.org/ bullseye-security main contrib non-free
    5: deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
  Active apt repos in: /etc/apt/sources.list.d/spotify.list
    1: deb http://repository.spotify.com stable non-free
Info:
  Processes: 232 Uptime: 9m wakeups: 0 Memory: 7.77 GiB used: 1.63 GiB
  (20.9%) Init: systemd v: 251 target: graphical (5) default: graphical
  Compilers: gcc: 10.2.1 alt: 10 clang: 11.0.1-2 Shell: Bash v: 5.1.4
  running-in: pty pts/0 (vt 7) inxi: 3.3.21
**************************************************************************************
apt list --installed | grep "elf"
 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
 
libelf-dev/bullseye-backports,now 0.187-1~bpo11+1 amd64 [installed]
libelf1/bullseye-backports,now 0.187-1~bpo11+1 amd64 [installed]
libelf1/bullseye-backports,now 0.187-1~bpo11+1 i386 [installed,automatic]
python3-pyelftools/stable,stable,now 0.27-1 all [installed]
 
**************************************************************************************
 
Oct 13 16:47:59 lmde5 kernel: Invalid ELF header magic: != ELF
Oct 13 16:47:59 lmde5 kernel: Invalid ELF header magic: != ELF
Oct 13 16:47:59 lmde5 kernel: Invalid ELF header magic: != ELF
Oct 13 16:47:59 lmde5 kernel: Invalid ELF header magic: != ELF
Oct 13 16:47:59 lmde5 kernel: Invalid ELF header magic: != ELF
Oct 13 16:47:59 lmde5 kernel: Invalid ELF header magic: != ELF
```

**Comment by damentz** [comment] 2022-10-14 00:55
@Tenebris-Umbra how are you installing Liquorix?  I don't see a liquorix.list file or a reference to liquorix.net.  If you use the install script from the official website, it'll autodetect your operating system and install the correct version.

**Comment by damentz** [comment] 2022-10-14 01:09
Per this commit on a fork of Linux for Qualcomm boards, this error is benign and shows up on specific variations of Busybox setups: https://gitlab.com/msm8998-mainline/linux/-/commit/4d39479eda066703ac650ce251f2d806de745101

Compression was recently activated in Liquorix so that some initrd's wouldn't blow up from being so large.  This output is caused by Busybox not recognizing the signature of the file and complaining.  When a file is compressed, it can't determine what it is and will complain regardless if it can successfully load a module with modprobe.

Marking as closed.

**Closed as completed by damentz** 2022-10-14 01:09 UTC

**Comment by Tenebris-Umbra** [comment] 2022-10-14 01:53
OK, Like I said everything is loading, inc nvidia dkms, and it runs with its usual speediness and snappiness. I have never seen this error, up and inc 5.19.14-1.  Any-who, in case you never get enough kudos's, THANK YOU VERY MUCH for all your work and your project. :-D 

P.S I download the deb's straight from the repo and install via sudo dpkg -i *.deb

**Comment by Tenebris-Umbra** [comment] 2022-10-19 19:37
Super!, I had a chance to install 5.19.16.2 and the error are indeed gone
